// @ts-ignore
const mongoose = require('mongoose');

// @ts-ignore
const Schema = mongoose.Schema;

//CREATING SCHEMA FOR 'STUDENT'
const activitySchema = new Schema({
    name: { type: String, required: true },
    surname: { type: String, required: true },
    id: { type: Number, required: true,},
    image: { type: String, required: true,},
    mail: { type: String, required: true,},
    password: { type: String, required: true,},
    phoneNumber: { type: Number, required: true,},
    citizenshipId: { type: Number, required: true,},
    registrationYear: { type: Number, required: true,},
    Department: { type: String, required: true,},
    RegistrationType: { type: String, required: true,},
    EducationLevel: { type: String, required: true,},

    //current course 1
    currentCourse1: { type: String, required: true,},
    currentCourse1Quiz: { type: Number, required: false,},
    currentCourse1Homework: { type: Number, required: false,},
    currentCourse1Project: { type: Number, required: false,},
    currentCourse1Midterm: { type: Number, required: false,},
    currentCourse1Final: { type: Number, required: false,},
    currentCourse1Total: { type: Number, required: false,},
    currentCourse1Makeup: { type: Number, required: false,},
    currentCourse1FinalGrade: { type: Number, required: false,},
    currentCourse1FinalLetterGrade: { type: String, required: false,},
    currentCourse1ClassAverage: { type: Number, required: false,},

    //current course 2
    currentCourse2: { type: String, required: true,},
    currentCourse2Quiz: { type: Number, required: false,},
    currentCourse2Homework: { type: Number, required: false,},
    currentCourse2Project: { type: Number, required: false,},
    currentCourse2Midterm: { type: Number, required: false,},
    currentCourse2Final: { type: Number, required: false,},
    currentCourse2Total: { type: Number, required: false,},
    currentCourse2Makeup: { type: Number, required: false,},
    currentCourse2FinalGrade: { type: Number, required: false,},
    currentCourse2FinalLetterGrade: { type: String, required: false,},
    currentCourse2ClassAverage: { type: Number, required: false,},

    //current course 3
    currentCourse3: { type: String, required: true,},
    currentCourse3Quiz: { type: Number, required: false,},
    currentCourse3Homework: { type: Number, required: false,},
    currentCourse3Project: { type: Number, required: false,},
    currentCourse3Midterm: { type: Number, required: false,},
    currentCourse3Final: { type: Number, required: false,},
    currentCourse3Total: { type: Number, required: false,},
    currentCourse3Makeup: { type: Number, required: false,},
    currentCourse3FinalGrade: { type: Number, required: false,},
    currentCourse3FinalLetterGrade: { type: String, required: false,},
    currentCourse3ClassAverage: { type: Number, required: false,},

    //current course 4
    currentCourse4: { type: String, required: true,},
    currentCourse4Quiz: { type: Number, required: false,},
    currentCourse4Homework: { type: Number, required: false,},
    currentCourse4Project: { type: Number, required: false,},
    currentCourse4Midterm: { type: Number, required: false,},
    currentCourse4Final: { type: Number, required: false,},
    currentCourse4Total: { type: Number, required: false,},
    currentCourse4Makeup: { type: Number, required: false,},
    currentCourse4FinalGrade: { type: Number, required: false,},
    currentCourse4FinalLetterGrade: { type: String, required: false,},
    currentCourse4ClassAverage: { type: Number, required: false,},

    //current course 5
    currentCourse5: { type: String, required: true,},
    currentCourse5Quiz: { type: Number, required: false,},
    currentCourse5Homework: { type: Number, required: false,},
    currentCourse5Project: { type: Number, required: false,},
    currentCourse5Midterm: { type: Number, required: false,},
    currentCourse5Final: { type: Number, required: false,},
    currentCourse5Total: { type: Number, required: false,},
    currentCourse5Makeup: { type: Number, required: false,},
    currentCourse5FinalGrade: { type: Number, required: false,},
    currentCourse5FinalLetterGrade: { type: String, required: false,},
    currentCourse5ClassAverage: { type: Number, required: false,},

    //current exam schedule
    currentExam1: { type: String, required: true,},
    currentCourse1Day: { type: String, required: true,},
    currentCourse1Time: { type: Number, required: true,},
    currentCourse1TimeEnd: { type: Number, required: true,},
    currentExam2: { type: String, required: true,},
    currentCourse2Day: { type: String, required: true,},
    currentCourse2Time: { type: Number, required: true,},
    currentCourse2TimeEnd: { type: Number, required: true,},
    currentExam3: { type: String, required: true,},
    currentCourse3Day: { type: String, required: true,},
    currentCourse3Time: { type: Number, required: true,},
    currentCourse3TimeEnd: { type: Number, required: true,},
    currentExam4: { type: String, required: true,},
    currentCourse4Day: { type: String, required: true,},
    currentCourse4Time: { type: Number, required: true,},
    currentCourse4TimeEnd: { type: Number, required: true,},
    currentExam5: { type: String, required: true,},
    currentCourse5Day: { type: String, required: true,},
    currentCourse5Time: { type: Number, required: true,},
    currentCourse5TimeEnd: { type: Number, required: true,},

    currentCourseName1: { type: String, required: true,},
    currentCourseName2: { type: String, required: true,},
    currentCourseName3: { type: String, required: true,},
    currentCourseName4: { type: String, required: true,},
    currentCourseName5: { type: String, required: true,},

    currentCourseSchedule1: { type: String, required: true,},
    currentCourseSchedule2: { type: String, required: true,},
    currentCourseSchedule3: { type: String, required: true,},
    currentCourseSchedule4: { type: String, required: true,},
    currentCourseSchedule5: { type: String, required: true,},

    takenCourse1: { type: String, required: true,},
    takenCourseName1: {type: String, required: true,},
    takenCourse1Quiz: { type: Number, required: true,},
    takenCourse1Homework: { type: Number, required: true,},
    takenCourse1Project: { type: Number, required: true,},
    takenCourse1Midterm: { type: Number, required: true,},
    takenCourse1Final: { type: Number, required: true,},
    takenCourse1Total: { type: Number, required: true,},
    takenCourse1Makeup: { type: Number, required: false,},
    takenCourse1FinalGrade: { type: Number, required: true,},
    takenCourse1FinalLetterGrade: { type: String, required: true,},
    takenCourse1ClassAverage: { type: Number, required: true,},

    takenCourse2: { type: String, required: true,},
    takenCourseName2: {type: String, required: true,},
    takenCourse2Quiz: { type: Number, required: true,},
    takenCourse2Homework: { type: Number, required: true,},
    takenCourse2Project: { type: Number, required: true,},
    takenCourse2Midterm: { type: Number, required: true,},
    takenCourse2Final: { type: Number, required: true,},
    takenCourse2Total: { type: Number, required: true,},
    takenCourse2Makeup: { type: Number, required: false,},
    takenCourse2FinalGrade: { type: Number, required: true,},
    takenCourse2FinalLetterGrade: { type: String, required: true,},
    takenCourse2ClassAverage: { type: Number, required: true,},

    takenCourse3: { type: String, required: true,},
    takenCourseName3: {type: String, required: true,},
    takenCourse3Quiz: { type: Number, required: true,},
    takenCourse3Homework: { type: Number, required: true,},
    takenCourse3Project: { type: Number, required: true,},
    takenCourse3Midterm: { type: Number, required: true,},
    takenCourse3Final: { type: Number, required: true,},
    takenCourse3Total: { type: Number, required: true,},
    takenCourse3Makeup: { type: Number, required: false,},
    takenCourse3FinalGrade: { type: Number, required: true,},
    takenCourse3FinalLetterGrade: { type: String, required: true,},
    takenCourse3ClassAverage: { type: Number, required: true,},

    takenCourse4: { type: String, required: true,},
    takenCourseName4: {type: String, required: true,},
    takenCourse4Quiz: { type: Number, required: true,},
    takenCourse4Homework: { type: Number, required: true,},
    takenCourse4Project: { type: Number, required: true,},
    takenCourse4Midterm: { type: Number, required: true,},
    takenCourse4Final: { type: Number, required: true,},
    takenCourse4Total: { type: Number, required: true,},
    takenCourse4Makeup: { type: Number, required: false,},
    takenCourse4FinalGrade: { type: Number, required: true,},
    takenCourse4FinalLetterGrade: { type: String, required: true,},
    takenCourse4ClassAverage: { type: Number, required: true,},

    takenCourse5: { type: String, required: true,},
    takenCourseName5: {type: String, required: true,},
    takenCourse5Quiz: { type: Number, required: true,},
    takenCourse5Homework: { type: Number, required: true,},
    takenCourse5Project: { type: Number, required: true,},
    takenCourse5Midterm: { type: Number, required: true,},
    takenCourse5Final: { type: Number, required: true,},
    takenCourse5Total: { type: Number, required: true,},
    takenCourse5Makeup: { type: Number, required: false,},
    takenCourse5FinalGrade: { type: Number, required: true,},
    takenCourse5FinalLetterGrade: { type: String, required: true,},
    takenCourse5ClassAverage: { type: Number, required: true,},

    takenCourse6: { type: String, required: true,},
    takenCourseName6: {type: String, required: true,},
    takenCourse6Quiz: { type: Number, required: true,},
    takenCourse6Homework: { type: Number, required: true,},
    takenCourse6Project: { type: Number, required: true,},
    takenCourse6Midterm: { type: Number, required: true,},
    takenCourse6Final: { type: Number, required: true,},
    takenCourse6Total: { type: Number, required: true,},
    takenCourse6Makeup: { type: Number, required: false,},
    takenCourse6FinalGrade: { type: Number, required: true,},
    takenCourse6FinalLetterGrade: { type: String, required: true,},
    takenCourse6ClassAverage: { type: Number, required: true,},

    takenCourse7: { type: String, required: true,},
    takenCourseName7: {type: String, required: true,},
    takenCourse7Quiz: { type: Number, required: true,},
    takenCourse7Homework: { type: Number, required: true,},
    takenCourse7Project: { type: Number, required: true,},
    takenCourse7Midterm: { type: Number, required: true,},
    takenCourse7Final: { type: Number, required: true,},
    takenCourse7Total: { type: Number, required: true,},
    takenCourse7Makeup: { type: Number, required: false,},
    takenCourse7FinalGrade: { type: Number, required: true,},
    takenCourse7FinalLetterGrade: { type: String, required: true,},
    takenCourse7ClassAverage: { type: Number, required: true,},

    takenCourse8: { type: String, required: true,},
    takenCourseName8: {type: String, required: true,},
    takenCourse8Quiz: { type: Number, required: true,},
    takenCourse8Homework: { type: Number, required: true,},
    takenCourse8Project: { type: Number, required: true,},
    takenCourse8Midterm: { type: Number, required: true,},
    takenCourse8Final: { type: Number, required: true,},
    takenCourse8Total: { type: Number, required: true,},
    takenCourse8Makeup: { type: Number, required: false,},
    takenCourse8FinalGrade: { type: Number, required: true,},
    takenCourse8FinalLetterGrade: { type: String, required: true,},
    takenCourse8ClassAverage: { type: Number, required: true,},

    takenCourse9: { type: String, required: true,},
    takenCourseName9: {type: String, required: true,},
    takenCourse9Quiz: { type: Number, required: true,},
    takenCourse9Homework: { type: Number, required: true,},
    takenCourse9Project: { type: Number, required: true,},
    takenCourse9Midterm: { type: Number, required: true,},
    takenCourse9Final: { type: Number, required: true,},
    takenCourse9Total: { type: Number, required: true,},
    takenCourse9Makeup: { type: Number, required: false,},
    takenCourse9FinalGrade: { type: Number, required: true,},
    takenCourse9FinalLetterGrade: { type: String, required: true,},
    takenCourse9ClassAverage: { type: Number, required: true,},

    takenCourse10: { type: String, required: true,},
    takenCourseName10: {type: String, required: true,},
    takenCourse10Quiz: { type: Number, required: true,},
    takenCourse10Homework: { type: Number, required: true,},
    takenCourse10Project: { type: Number, required: true,},
    takenCourse10Midterm: { type: Number, required: true,},
    takenCourse10Final: { type: Number, required: true,},
    takenCourse10Total: { type: Number, required: true,},
    takenCourse10Makeup: { type: Number, required: false,},
    takenCourse10FinalGrade: { type: Number, required: true,},
    takenCourse10FinalLetterGrade: { type: String, required: true,},
    takenCourse10ClassAverage: { type: Number, required: true,},

    takenCourse11: { type: String, required: true,},
    takenCourseName11: {type: String, required: true,},
    takenCourse11Quiz: { type: Number, required: true,},
    takenCourse11Homework: { type: Number, required: true,},
    takenCourse11Project: { type: Number, required: true,},
    takenCourse11Midterm: { type: Number, required: true,},
    takenCourse11Final: { type: Number, required: true,},
    takenCourse11Total: { type: Number, required: true,},
    takenCourse11Makeup: { type: Number, required: false,},
    takenCourse11FinalGrade: { type: Number, required: true,},
    takenCourse11FinalLetterGrade: { type: String, required: true,},
    takenCourse11ClassAverage: { type: Number, required: true,},

    takenCourse12: { type: String, required: true,},
    takenCourseName12: {type: String, required: true,},
    takenCourse12Quiz: { type: Number, required: true,},
    takenCourse12Homework: { type: Number, required: true,},
    takenCourse12Project: { type: Number, required: true,},
    takenCourse12Midterm: { type: Number, required: true,},
    takenCourse12Final: { type: Number, required: true,},
    takenCourse12Total: { type: Number, required: true,},
    takenCourse12Makeup: { type: Number, required: false,},
    takenCourse12FinalGrade: { type: Number, required: true,},
    takenCourse12FinalLetterGrade: { type: String, required: true,},
    takenCourse12ClassAverage: { type: Number, required: true,},

    takenCourse13: { type: String, required: true,},
    takenCourseName13: {type: String, required: true,},
    takenCourse13Quiz: { type: Number, required: true,},
    takenCourse13Homework: { type: Number, required: true,},
    takenCourse13Project: { type: Number, required: true,},
    takenCourse13Midterm: { type: Number, required: true,},
    takenCourse13Final: { type: Number, required: true,},
    takenCourse13Total: { type: Number, required: true,},
    takenCourse13Makeup: { type: Number, required: false,},
    takenCourse13FinalGrade: { type: Number, required: true,},
    takenCourse13FinalLetterGrade: { type: String, required: true,},
    takenCourse13ClassAverage: { type: Number, required: true,},

    takenCourse14: { type: String, required: true,},
    takenCourseName14: {type: String, required: true,},
    takenCourse14Quiz: { type: Number, required: true,},
    takenCourse14Homework: { type: Number, required: true,},
    takenCourse14Project: { type: Number, required: true,},
    takenCourse14Midterm: { type: Number, required: true,},
    takenCourse14Final: { type: Number, required: true,},
    takenCourse14Total: { type: Number, required: true,},
    takenCourse14Makeup: { type: Number, required: false,},
    takenCourse14FinalGrade: { type: Number, required: true,},
    takenCourse14FinalLetterGrade: { type: String, required: true,},
    takenCourse14ClassAverage: { type: Number, required: true,},

    takenCourse15: { type: String, required: true,},
    takenCourseName15: {type: String, required: true,},
    takenCourse15Quiz: { type: Number, required: true,},
    takenCourse15Homework: { type: Number, required: true,},
    takenCourse15Project: { type: Number, required: true,},
    takenCourse15Midterm: { type: Number, required: true,},
    takenCourse15Final: { type: Number, required: true,},
    takenCourse15Total: { type: Number, required: true,},
    takenCourse15Makeup: { type: Number, required: false,},
    takenCourse15FinalGrade: { type: Number, required: true,},
    takenCourse15FinalLetterGrade: { type: String, required: true,},
    takenCourse15ClassAverage: { type: Number, required: true,},

    takenCourse16: { type: String, required: true,},
    takenCourseName16: {type: String, required: true,},
    takenCourse16Quiz: { type: Number, required: true,},
    takenCourse16Homework: { type: Number, required: true,},
    takenCourse16Project: { type: Number, required: true,},
    takenCourse16Midterm: { type: Number, required: true,},
    takenCourse16Final: { type: Number, required: true,},
    takenCourse16Total: { type: Number, required: true,},
    takenCourse16Makeup: { type: Number, required: false,},
    takenCourse16FinalGrade: { type: Number, required: true,},
    takenCourse16FinalLetterGrade: { type: String, required: true,},
    takenCourse16ClassAverage: { type: Number, required: true,},

    takenCourse17: { type: String, required: true,},
    takenCourseName17: {type: String, required: true,},
    takenCourse17Quiz: { type: Number, required: true,},
    takenCourse17Homework: { type: Number, required: true,},
    takenCourse17Project: { type: Number, required: true,},
    takenCourse17Midterm: { type: Number, required: true,},
    takenCourse17Final: { type: Number, required: true,},
    takenCourse17Total: { type: Number, required: true,},
    takenCourse17Makeup: { type: Number, required: false,},
    takenCourse17FinalGrade: { type: Number, required: true,},
    takenCourse17FinalLetterGrade: { type: String, required: true,},
    takenCourse17ClassAverage: { type: Number, required: true,},

    takenCourse18: { type: String, required: true,},
    takenCourseName18: {type: String, required: true,},
    takenCourse18Quiz: { type: Number, required: true,},
    takenCourse18Homework: { type: Number, required: true,},
    takenCourse18Project: { type: Number, required: true,},
    takenCourse18Midterm: { type: Number, required: true,},
    takenCourse18Final: { type: Number, required: true,},
    takenCourse18Total: { type: Number, required: true,},
    takenCourse18Makeup: { type: Number, required: false,},
    takenCourse18FinalGrade: { type: Number, required: true,},
    takenCourse18FinalLetterGrade: { type: String, required: true,},
    takenCourse18ClassAverage: { type: Number, required: true,},

    takenCourse19: { type: String, required: true,},
    takenCourseName19: {type: String, required: true,},
    takenCourse19Quiz: { type: Number, required: true,},
    takenCourse19Homework: { type: Number, required: true,},
    takenCourse19Project: { type: Number, required: true,},
    takenCourse19Midterm: { type: Number, required: true,},
    takenCourse19Final: { type: Number, required: true,},
    takenCourse19Total: { type: Number, required: true,},
    takenCourse19Makeup: { type: Number, required: false,},
    takenCourse19FinalGrade: { type: Number, required: true,},
    takenCourse19FinalLetterGrade: { type: String, required: true,},
    takenCourse19ClassAverage: { type: Number, required: true,},

    takenCourse20: { type: String, required: true,},
    takenCourseName20: {type: String, required: true,},
    takenCourse20Quiz: { type: Number, required: true,},
    takenCourse20Homework: { type: Number, required: true,},
    takenCourse20Project: { type: Number, required: true,},
    takenCourse20Midterm: { type: Number, required: true,},
    takenCourse20Final: { type: Number, required: true,},
    takenCourse20Total: { type: Number, required: true,},
    takenCourse20Makeup: { type: Number, required: false,},
    takenCourse20FinalGrade: { type: Number, required: true,},
    takenCourse20FinalLetterGrade: { type: String, required: true,},
    takenCourse20ClassAverage: { type: Number, required: true,},

});

module.exports = mongoose.model('Students', activitySchema);